name: Deploy

on:
  push:
    branches:
      - master  # Trigger this workflow on push events to the main branch

jobs:
  deploy:
    name: Deploy files to server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Deploy to server
      id: deploy
      uses: Pendect/action-rsyncer@latest
      env:
        DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
      with:
        flags: '-avzr --delete'
        options: ''
        ssh_options: ''
        src: 'public/'
        dest: 'user@server.com:/var/www/server.com'

- name: Display status from deploy
  run: echo "${{ steps.deploy.outputs.status }}"

    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        protocol: ftps
        port: 22
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        server-dir: /var/www/html/bom/

    - name: Restart service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PASSWORD }}
        script: ${{ vars.RESTART_SCRIPT }}