name: Deploy

on:
  push:
    branches:
      - master  # Trigger this workflow on push events to the main branch

jobs:
  deploy:
    name: Deploy files to server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        server-dir: /var/www/html/bom/

    - name: Restart service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        protocol: ${{ secrets.SSH_PROTOCOL }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PASSWORD }}
        script: ${{ vars.RESTART_SCRIPT }}