name: Deploy

on:
  push:
    branches:
      - master  # Trigger this workflow on push events to the main branch

jobs:
  deploy:
    name: Deploy files to server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.USERNAME }}
        FTP_PASSWORD: ${{ secrets.PASSWORD }}
        REMOTE_DIR: /var/www/html/bom/
        METHOD: sftp
        PORT: 22
        ARGS: --verbose

      # with:
      #   server: ${{ secrets.FTP_SERVER }}
      #   protocol: ftp
      #   port: 22
      #   username: ${{ secrets.USERNAME }}
      #   password: ${{ secrets.PASSWORD }}
      #   server-dir: /var/www/html/bom/

    - name: Restart service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: ${{ vars.RESTART_SCRIPT }}